#!/bin/bash
CMD="java -ea -cp classes:lib/* -Dh2.allowedClasses=jw.jzbot.PublicDatabaseUtils -Dsun.net.inetaddr.ttl=10 jw.jzbot.JZBot $*"
echo 
echo Running with command $CMD
echo 
$CMD
while [ $? == '17' ]
do
  $CMD
  sleep 5
done
