#!/bin/bash
echo Downloading updates from origin...
old=`git rev-parse HEAD`
git pull --ff-only
new=`git rev-parse HEAD`
git log --pretty='format:http://github.com/javawizard/jzbot/commit/%h %s' "$old..$new" > storage/update-log
echo Removing existing classes...
rm -rf classes
echo Building JZBot...
./build
echo Updating to the latest version of JZBot... > storage/restart-temp
rm -rf storage/restart
mv storage/restart-temp storage/restart
echo Updates have completed successfully. If your bot
echo is currently running, it will restart itself momentarily.

