#!/bin/bash


# First, we need to actually build JZBot.
ant archive

#Now we'll do the uploading.
targethost="bztraining.org"
targetportstring=""
echo Settings: targethost is $targethost and targetportstring is $targetportstring
echo About to upload. Enter your password when asked.
rsync -vvv -e "ssh${targetportstring}" jzbot2-old.tar jcp@${targethost}:/home/jcp/jzbot2-old.tar
echo About to extract. Enter your password when asked.
ssh${targetportstring} jcp@${targethost} /home/jcp/jzbot-reload
